name: vit_register_neurons
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.9
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.0
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.14.0.30
  - libcurand=10.3.10.19
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cachetools==6.0.0
      - contourpy==1.3.2
      - cubinlinker-cu11==0.3.0.post3
      - cuda-bindings==11.8.7
      - cuda-python==11.8.7
      - cudf-cu11==25.4.0
      - cuml-cu11==25.4.0
      - cupy-cuda11x==13.4.1
      - cuvs-cu11==25.4.0
      - dask==2025.2.0
      - dask-cuda==25.4.0
      - dask-cudf-cu11==25.4.0
      - diffusers==0.33.1
      - distributed==2025.2.0
      - distributed-ucxx-cu11==0.43.0
      - einops==0.8.1
      - fastrlock==0.8.3
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - h5py==3.13.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.1
      - imageio==2.37.0
      - iopath==0.1.10
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - libcudf-cu11==25.4.0
      - libcuml-cu11==25.4.0
      - libcuvs-cu11==25.4.0
      - libkvikio-cu11==25.4.0
      - libraft-cu11==25.4.0
      - librmm-cu11==25.4.0
      - libucx-cu11==1.18.1
      - libucxx-cu11==0.43.0
      - matplotlib==3.10.3
      - msgpack==1.1.0
      - numba-cuda==0.4.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.575.51
      - nvidia-nvcomp-cu11==4.2.0.11
      - nvtx==0.2.12
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - portalocker==3.1.1
      - ptxcompiler-cu11==0.8.1.post3
      - pylibcudf-cu11==25.4.0
      - pylibraft-cu11==25.4.0
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pyre-extensions==0.0.23
      - raft-dask-cu11==25.4.0
      - rapids-dask-dependency==25.4.0
      - rapids-logger==0.1.1
      - regex==2024.11.6
      - rmm-cu11==25.4.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentence-transformers==4.1.0
      - sortedcontainers==2.4.0
      - submitit==1.5.3
      - tabulate==0.9.0
      - tblib==3.1.0
      - termcolor==3.1.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - torchmetrics==0.10.3
      - tqdm==4.67.1
      - transformers==4.52.3
      - treelite==4.4.1
      - typing-inspect==0.9.0
      - ucx-py-cu11==0.43.0
      - ucxx-cu11==0.43.0
      - xformers==0.0.18
      - yacs==0.1.8
      - zict==3.0.0